### ISSUE TITLE
Not working with @include

### ISSUE THREAD

**Issue by mspoulsen** [adam1658/jest-transform-nearley#1]
Hi,

When I try to use the @include directive  like this:

````
@include "primitives.ne"

foo   -> "foo"
````

Then I get:

`TypeError: Cannot read property '0' of undefined`

```
import grammar from '@/grammar/foo.ne'
^
```

Is this possible to fix?

Thanks!

**Comment by adam1658** [comment]
Hi @mspoulsen,

I've published a v2 which correctly resolves includes relative to the current file.

It used to (incorrectly in my opinion) resolve them relative to the cwd.

Let me know if you have any further troubles with it.

Thanks,
Adam

**Comment by mspoulsen** [comment]
Thanks a lot! Will try it out :+1:

**Comment by mspoulsen** [comment]
It is working...kind of. I have problems with changes not loading between test runs.

I have a.ne that includes b.ne. When I run test for a.ne then updates in b.ne are not updated between test runs. However, if I compile the ne file and require the .js file it works as expected.

Any chance you now how to fix nearley-loader?
It is not working with @include and nobody seems to be fixing bugs there :disappointed: 
https://github.com/kozily/nearley-loader/issues/8

**Comment by adam1658** [comment]
I haven't done a lot of work with nearley. I'll have a look at the include updates issue soon - I've got a few ideas. I suspect that Jest doesn't redo the transform on `a.ne` when `b.ne` changes, because it doesn't know that `a.ne` is affected by `b.ne`.
